GET http://localhost:5000/todos 

###
####
POST http://localhost:5000/todo/new 
content-type: application/json

{
    "text" : "Dish Kazhikal"
}
###

DELETE http://localhost:5000/todo/delete/657d4bd08c0c87c88a7ffce5

###
PUT http://localhost:5000/todo/complete/657d4b678c0c87c88a7ffce3